### ISSUE TITLE
Support for replacing and saving ARC and its contents

### ISSUE THREAD

**Issue by Struggleton** [ScanMountGoat/ArcExplorer#12]
Currently, ArcInstaller only can inject files with the same size or less than the original file. While ARCropolis is a great solution on console, it (at the current moment of writing this!) is not supported on either Ryujinx or Yuzu. Full on modding has been one of the  goals from the outset of the Yuzu community and this could provide a solution in that field.

**Comment by jam1garner** [comment]
Skyline support in Ryujinx is being worked on, I'd argue that will be a better solution for modding in an emulator

**Comment by Struggleton** [comment]
Whether you do or don't, your contribution to modding is super appreciated! loved the writeup on smash-arc in Rust
