### ISSUE TITLE
Different trailing slashes for directories

### ISSUE THREAD

**Issue by ScanMountGoat** [ScanMountGoat/ArcExplorer#13]
`render/shader` and `render/shader/` (trailing slash) are considered different directories. It doesn't make sense to handle this in smash-arc or SmashArcNet since the entries are distinct. It should be doable to handle this automatically from ArcExplorer itself.
- [x] When typing a path like "a/b/c", load the nodes for both "a/b/c" and "a/b/c/" (trailing slash)
- [x] When loading child nodes, strip trailing slashes from directories and remove duplicates by path
- [x] When extracting the folder "a/b/c", extract the nodes from "a/b/c" and "a/b/c/" (trailing slash)
- [x] Add an option in preferences to keep them separate (should be disabled by default)

**Comment by zrksyd** [comment]
![image](https://user-images.githubusercontent.com/6856627/114250208-f02d0f00-996a-11eb-858d-45b7a30fb0c9.png)
Is that related to this?

**Comment by jam1garner** [comment]
yes @zrksyd. since the paths are "different" they show as different folders.
