### ISSUE TITLE
Lacking features that are in CrossArc

### ISSUE THREAD

**Issue by mnsg23** [ScanMountGoat/ArcExplorer#14]
I recently downloaded Arc Explorer, but I noticed that it's lacking some features that are available in CrossArc.

1. It's not possible to update the hashes. That's going to be important when new software updates get released.
2. There's no option to change the language. When extracting language files from Arc Explorer, you're restricted to only the North American English files.

**Comment by ScanMountGoat** [comment]
I'm closing this as related issues already exist. If you have any other potential feature requests, post a separate issue. 
1. This is a planned feature. The current hashes are up to date as of posting this comment. See #1 
2. Regional files haven't been implemented yet but hopefully will be soon. See #3
