### ISSUE TITLE
SIGSEGV when trying to open file selection dialogue in any way (Artix Linux)

### ISSUE THREAD

**Issue by CoatlessEskimo** [ScanMountGoat/ArcExplorer#18]
Crashes when trying to open file dialogue to select the data.arc, or extraction default folder. `log.txt` is empty. 

`fish: './ArcExplorer' terminated by signal SIGSEGV (Address boundary error)`

`dotnet --list-runtimes` shows `Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]` as an available runtime.

**Comment by ScanMountGoat** [comment]
Apparently this is a known issue for Avalonia 9.x 
https://github.com/AvaloniaUI/Avalonia/issues/2817

**Comment by CoatlessEskimo** [comment]
How would I go about this?

**Comment by ScanMountGoat** [comment]
I'll try and have it fixed for the next release of Arc Explorer, so there's nothing you need to do on your end other than try it out when that releases.  You can try some of the workarounds in the link if you're able to build ArcExplorer from source.

**Comment by ScanMountGoat** [comment]
This may be fixed on the latest release due to updating the UI library. I don't have a way to test on that specific linux distro at the moment. https://github.com/ScanMountGoat/ArcExplorer/releases/tag/v1.1.0.

**Comment by CoatlessEskimo** [comment]
Problem fixed. File selection dialogue now opens properly.

**Comment by ScanMountGoat** [comment]
Glad to hear it.
