### ISSUE TITLE
Failed to open ARC file

### ISSUE THREAD

**Issue by christian062** [ScanMountGoat/ArcExplorer#21]
Errors message, it won't even view data.arc
![bandicam 2021-01-31 17-42-46-309](https://user-images.githubusercontent.com/69006453/106400721-35bee000-63ee-11eb-9355-4700c4fb807c.jpg)

**Comment by ScanMountGoat** [comment]
What version of the data.arc are you trying to open? The earliest that I know of that works is from game version 4.0.

**Comment by christian062** [comment]
I was using the one for the base game since my XCI file did not let me dump
the files with dlc. Smash Ultimate base game data.arc.

**Comment by ScanMountGoat** [comment]
ArcExplorer doesn't support that ARC version. If you need to open a version 1.0 ARC and are able to run windows, you can use [Cross Arc](https://github.com/Ploaj/ArcCross/releases).

**Comment by christian062** [comment]
![bandicam 2021-02-01 16-45-57-683](https://user-images.githubusercontent.com/69006453/106521944-fa371b00-64ac-11eb-9965-0aed389ebc4a.jpg)

**Comment by ScanMountGoat** [comment]
The ARC file not not have been dumped correctly. You can find guides on [gamebanana](https://gamebanana.com/games/6498). There's also a link to the discord where you can ask for help. Github issues is for feature requests or reporting bugs with ArcExplorer itself. If you need help dumping the game, asking in discord is probably the best option.

**Comment by christian062** [comment]
What is the discord link?

**Comment by ScanMountGoat** [comment]
It's on the main page if you use the gamebanana link. https://discord.gg/ASJyTrZ
