### ISSUE TITLE
Problems with opening the data.arc file

### ISSUE THREAD

**Issue by Mezoda** [ScanMountGoat/ArcExplorer#27]
I've been having alot of issues with opening the data.arc file in ArcExplorer which gives me errors upon attempting to open it. I'm very confused on what's going on.

![image](https://user-images.githubusercontent.com/51860087/122832693-bb69fc00-d2b9-11eb-87ae-d0d999f087bd.png)

Everytime I try to merge the base game with the update file it always gives me the filesize as seen above no matter what I try. If anyone can give me advice on what to do then I would be VERY grateful. Thanks.

**Comment by ScanMountGoat** [comment]
How are you applying the update? It sounds like your file isn't correct, so there's no way for ArcExplorer to read it. This isn't something we can really fix on our end, so I'd recommend joining the modding discord and asking in the #help channel. https://discord.gg/ASJyTrZ

**Comment by ScanMountGoat** [comment]
Closing as this is not application related. After getting the ARC file creation sorted out, feel free to post any other issues you encounter while using the program.
