### ISSUE TITLE
ArcExplorer still wont launch

### ISSUE THREAD

**Issue by NeckGod00** [ScanMountGoat/ArcExplorer#56]
I already downloaded the windows desktop runtime but it wont launch still was there a specific one i supposed to dl. i chose rundesktop apps but i didnt know if i should choose x64 or x86

**Comment by ScanMountGoat** [comment]
Try with x64. Someone had a similar issue on another program and that fixed it. Let me know if you're still having issues after trying x64. I may need to update the installation instructions if this becomes a common issue.

**Comment by NeckGod00** [comment]
Yeah im using only x64 now and it wont launch the application still

**Comment by ScanMountGoat** [comment]
I'm able to reproduce this on a clean build but not on my normal windows PC. Can you try running `dotnet ArcExplorer.dll` in command prompt from the directory with ArcExplorer.exe? This is an alternative method to launch the program, and it should print some sort of error.

**Comment by ScanMountGoat** [comment]
This is fixed if you redownload the latest build for windows from the releases tab.
