### ISSUE TITLE
Unable to access regional Smash Taunt files

### ISSUE THREAD

**Issue by ThatNintendoNerd** [ScanMountGoat/ArcExplorer#64]
The files in `stream:/sound/smashappeal/` have different contents for the west, east, and on occasion, Europe. ArcExplorer is unable to access the other regions beyond just Japanese, and setting different regions and re-extracting does not extract the proper file. All regions were tested, and the Japanese variant of the file is only what gets extracted. I recall reading something about regional versus localized files, where regional actually entails three regions, so that may or may not be relevant here.

**Comment by ThatNintendoNerd** [comment]
A [pull request](https://github.com/jam1garner/smash-arc/pull/12) was recently merged into the smash-arc repository that should resolve this issue among other various files that were unable to be extracted before due to being localized, such as `ui/replace_patch/stage/stage_0/stage_0_ff_cave.bntx`.

**Comment by ScanMountGoat** [comment]
Fixed on latest commit.
