### ISSUE TITLE
Unable to Export all character assets.

### ISSUE THREAD

**Issue by ValkenEX** [ScanMountGoat/ArcExplorer#67]
I am only able to export a set amount of assets per character

alp_name_001_col.nutexb
alp_name_002_col.nutexb
alp_name_001_prm.nutexb
alp_name_001_col.nutexb
alp_name_001_nor.nutexb

I tried this on three characters, and I can only export those files specifically. Furthermore, it seems that attempting to export another file, like, say... 

def_name_001_col.nutexb 

it will export the alp_name_001_col.nutexb regardless of the file chosen.

**Comment by ScanMountGoat** [comment]
I'm not able to reproduce this on version 1.4.1. Is the application showing any errors? What specific files are you trying to extract?
