### ISSUE TITLE
how to get data.arc ????/?//???/?

### ISSUE THREAD

**Issue by TFLTV** [ScanMountGoat/ArcExplorer#69]
this probably makes me look stupid

edit: got issue #69

**Comment by ScanMountGoat** [comment]
You need to dump the data.arc from your copy of Smash Ultimate or follow the steps on the README to open the data.arc over the network. If you need help, check the gamebanana guides or ask on the modding discord. The discord is linked on the Smash Ultimate page for gamebanana.
