### ISSUE TITLE
Searching searches for files outside of folder

### ISSUE THREAD

**Issue by Segtendo** [ScanMountGoat/ArcExplorer#70]
Yo.

I've always noticed a weird bug with ARCExplorer with its search function.
![image](https://user-images.githubusercontent.com/76792055/183767503-f21f85e2-d2a3-49a2-81b5-8a28f0f987c9.png)
(Image is from 1.4.1, but it's the same in 1.4.2)

I search for `mario` in the fighter_voice folder, but it pulls up everything with that name _outside_ of the folder.

**Comment by ScanMountGoat** [comment]
This is intentional. The search functionality searches the entire ARC rather than the current folder. I think the confusion is that the search bar is on the same line as the current folder path. I'll look into reworking the layout in the future.
