### ISSUE TITLE
CrossMod Doesn't Load

### ISSUE THREAD

**Issue by SMABSYSTEMS** [ScanMountGoat/ArcExplorer#72]
So I got that message where I need to download Microsoft .NET, so I downloaded the .NET and after that the Visual C++ 2015 thing, but after I startup CrossMod, it doesn't give an error message, but I see this weird window (see attached file) for some seconds and then it just dissappears.... What should I do?

![help2](https://user-images.githubusercontent.com/84009225/184844221-87b2da4b-4027-4164-b8f8-3c566f41ba3c.PNG)
?

I tried out ssbh Editor, but that one doesn't load the textures on the model...

**Comment by ScanMountGoat** [comment]
This is the ArcExplorer repository, which doesn't require .NET to be installed. Cross Mod is no longer maintained, so you should switch to SSBH Editor. If you're having issues with SSBH Editor, please make an issue with details on what files you're trying to load here: https://github.com/ScanMountGoat/ssbh_editor/issues

**Comment by SMABSYSTEMS** [comment]
> This is the ArcExplorer repository, which doesn't require .NET to be installed. Cross Mod is no longer maintained, so you should switch to SSBH Editor. If you're having issues with SSBH Editor, please make an issue with details on what files you're trying to load here: https://github.com/ScanMountGoat/ssbh_editor/issues

I already did that :D However I had a problem with SSBH too (it loaded fine), so I'll ask about that there then
