### ISSUE TITLE
Unable to open arc file

### ISSUE THREAD

**Issue by Bramdoir** [ScanMountGoat/ArcExplorer#73]
Whenever I try to open the arc file, I simply get the error "Failed to open ARC file C:\Users\(MY NAME)\AppData\Roaming\yuzu\dump\01006A800016E000\romfs\data.arc". ArcExplorer is installed in "C:\ArcExplorer". The latest hashes have been installed. The log provides no additional information.

There's probably just something stupid I overlooked, but I can't see what. I've also tried using CrossArc instead, which gives a number of errors.

EDIT: nevermind, probably something wrong with the .arc file.

**Comment by ScanMountGoat** [comment]
Some older arc versions aren't supported. Make sure your game is up to date and your data.arc isn't corrupted. For Windows, run `certutil -hashfile data.arc MD5` from cmd. It should match one of the hashes listed on https://gist.github.com/ThatNintendoNerd/2eff671ecbafd2043e9e48758a6e61bd
