### ISSUE TITLE
Can't connect to switch

### ISSUE THREAD

**Issue by mlimmvfp1** [ScanMountGoat/ArcExplorer#75]
I believe I followed the appropriate steps - trying to use for 'one slot effect mod' for smash
- transferred the nro files for both the one slot effect and arc files to skyline > plugin (on my switch SD card)
- have both switch and laptop connected to same Network
- but when I put the IP address, it either fails to connect or is stuck on attempting to connect

Any ideas what might be wrong? I just downloaded skyline, so it should be the latest version

**Comment by ScanMountGoat** [comment]
I would double check that the IP address is correct. If you're still having issues, I would recommend asking on the smash ultimate modding discord to see if you installed everything correctly or there are some conflicts causing issues. I don't use the network feature personally, so I'm not really able to assist any further. https://discord.gg/ASJyTrZ
