### ISSUE TITLE
it says failed to open ARC file and i don't know why

### ISSUE THREAD

**Issue by Azimura82** [ScanMountGoat/ArcExplorer#78]
i don't know how or what is happening but it's driving me crazy please help (i've already searched on google and found nothing)
here is the log

[log.txt](https://github.com/ScanMountGoat/ArcExplorer/files/12137373/log.txt)

**Comment by ScanMountGoat** [comment]
Make sure your file is dumped correctly and isn't corrupted by checking the hash. 
tutorial: https://gamebanana.com/tuts/12827
MD5 Hashes: https://gist.github.com/ThatNintendoNerd/2eff671ecbafd2043e9e48758a6e61bd
