### ISSUE TITLE
App does not show files contained in .arc file after opening

### ISSUE THREAD

**Issue by impossibleguy** [ScanMountGoat/ArcExplorer#80]
Copy of ArcExplorer previously working stopped working after accepting some kind of update popup that involved New Donk City Hall. 

Occurring on a Windows 11 Home, version 10.0.22621 Build 22621

Attempted fixes:
- Restarting computer
- Deleting and reinstalling ArcExplorer 1.4.4
- Making sure the .arc file is valid (17,600,800,616 bytes and a good 13.0.1 MD5 hash)
- dumping a new .arc file
- deleting %localappdata%/ArcExplorer

Video of this happening: https://github.com/ScanMountGoat/ArcExplorer/assets/70489680/b315d2bd-0eba-405f-b034-58a0288a8bf2

Some other screenshots:

![Screenshot 2023-08-28 212312](https://github.com/ScanMountGoat/ArcExplorer/assets/70489680/df215e8a-5f0d-4776-85fd-9f81b186099f)
![Screenshot 2023-08-28 211742](https://github.com/ScanMountGoat/ArcExplorer/assets/70489680/f89c19fe-de90-4a7a-9675-4421dfe2cf9e)

**Comment by ScanMountGoat** [comment]
Do you get any errors when opening the arc file? Your data.arc is probably fine if you verified the checksum. The only thing I can think of is that the hashes got messed up somehow. If you delete the hashes.txt file from `%localappdata%/ArcExplorer`, it should download the latest file the next time you open the application.

**Comment by impossibleguy** [comment]
I did not get any errors, and we tried deleting the entirety of the %localappdata%/ArcExplore folder, which should have included the hashes.txt file

**Comment by ScanMountGoat** [comment]
Are you able to see the files on one of the more recent 1.4.x versions in releases? I would also check that the hashes.txt file is correct.

**Comment by impossibleguy** [comment]
I have confirmed that the hashes.txt file was included in the deletion. What would you like me to do with the 1.4.x files?

**Comment by ScanMountGoat** [comment]
Check with a text editor like notepad that the hashes.txt file looks ok. I would also try with 1.4.0, which you can download from releases.
